common/models/Course.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "course".
 *
 * @property integer $id
 * @property integer $season_id
 * @property string $title
 * @property string $description
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Season $season
 * @property Exam[] $exams
 * @property UserCourse[] $userCourses
 */
class Course extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%course}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['season_id', 'title'], 'required'],
            [['season_id', 'status', 'created_at', 'updated_at'], 'integer'],
            [['title', 'description'], 'string', 'max' => 255],
            [['title'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'season_id' => 'Season ID',
            'title' => 'Title',
            'description' => 'Description',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Returns active Seasons as array[id, title]
     * @return array
     */
    public function getSeasons()
    {
        $seasons = [];
        foreach (Season::find()->where(['status' => 1])->each() as $season) {
            $seasons[$season->id] = $season->title;
        }
        return $seasons;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSeason()
    {
        return $this->hasOne(Season::className(), ['id' => 'season_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExams()
    {
        return $this->hasMany(Exam::className(), ['course_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])
            ->viaTable(UserCourse::tableName(), ['course_id' => 'id']);
    }

    public function getUsersIdArray()
    {
        $users = $this->getUsers()->where(['>', 'status', 0])->asArray()->all();
        return ArrayHelper::map($users, 'id', 'id');
    }

    /**
     * Check if user with $userId is signed up on course
     * @param $userId integer
     * @return bool
     */
    public function isUserSigned($userId)
    {
        return ArrayHelper::keyExists($userId, $this->getUsersIdArray());
    }
}

backend/controllers/CourseController.php
<?php

namespace backend\controllers;

use common\models\Exam;
use common\models\Season;
use Yii;
use common\models\Course;
use common\models\CourseSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * CourseController implements the CRUD actions for Course model.
 */
class CourseController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Course models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CourseSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'newCourse' => new Course(),
            'seasonsList' => $this->getSeasonsList(),
        ]);
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (!Yii::$app->user->can('viewCourse')) {
            Yii::$app->session->setFlash('error', 'You do not have permission for this action.');
            return $this->redirect(['index']);
        }

        $seasonsList = null;
        if (Yii::$app->user->can('updateCourse')) {
            $seasonsList = $this->getSeasonsList();
        }

        $model = $this->findModel($id);
        $exams = $model->exams;

        return $this->render('view', [
            'model' => $model,
            'seasonsList' => $seasonsList,
            'exams' => $exams,
            'newExam' => new Exam(),
        ]);
    }

    /**
     * Creates a new Course model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->can('createCourse')) {
            Yii::$app->session->setFlash('error', 'You do not have permission for this action.');
            return $this->redirect(['index']);
        }

        $model = new Course();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                Yii::$app->response->data = $model->toArray(['id', 'season_id', 'title', 'description']);
            } else {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                Yii::$app->response->data = ['message' => 'Error occurred!'];
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'seasonsList' => $this->getSeasonsList(),
                ]);
            }
        }
    }

    /**
     * Updates an existing Course model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (!Yii::$app->user->can('updateCourse')) {
            Yii::$app->session->setFlash('error', 'You do not have permission for this action.');
            return $this->redirect(['index']);
        }

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                Yii::$app->response->data = $model->toArray(['id', 'season_id', 'title', 'description']);
                Yii::$app->response->data['season_title'] = $model->season->title;
            } else {
                return $this->redirect(['view', 'id' => $model->id]);

            }
        } else {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                Yii::$app->response->data = ['message' => 'Error occurred!'];
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'seasonsList' => $this->getSeasonsList(),
                ]);
            }
        }
    }

    /**
     * Deletes an existing Course model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!Yii::$app->user->can('deleteCourse')) {
            Yii::$app->session->setFlash('error', 'You do not have permission for this action.');
            return $this->redirect(['index']);
        }

        $model = $this->findModel($id);
        $model->status = 0;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Hard-Deletes an existing Course model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeletehard($id)
    {
        if (!Yii::$app->user->can('deleteCourse')) {
            Yii::$app->session->setFlash('error', 'You do not have permission for this action.');
            return $this->redirect(['index']);
        }

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Returned array [id, title] of seasons
     * @return array
     */
    protected function getSeasonsList()
    {
        $seasons = Season::find()->where(['status' => 1])->asArray()->all();
        $seasonsList = ArrayHelper::map($seasons, 'id', 'title');
        return $seasonsList;
    }
}

frontend/controllers/CourseController.php
<?php
/**
 * Created by PhpStorm.
 * User: oleg
 * Date: 31.01.16
 * Time: 18:09
 */

namespace frontend\controllers;


use common\models\Course;
use common\models\QuestionSearch;
use common\models\UserCourse;
use Yii;
use yii\web\Controller;
use common\models\CourseSearch;
use yii\web\NotFoundHttpException;

class CourseController extends Controller
{

    /**
     * Lists all Course models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryParams = Yii::$app->request->queryParams;
        $searchModel = new CourseSearch();
        $dataProvider = $searchModel->search($queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $exams = $model->exams;

        $questionSearchModel = new QuestionSearch();
        $questionDataProvider = $questionSearchModel->search([]);

        return $this->render('view', [
            'model' => $model,
            'exams' => $exams,
            'questionDataProvider' => $questionDataProvider,
        ]);
    }

    /**
     * Signing up user to course
     * @param $id integer course id
     */
    public function actionSignup($id)
    {
        if (yii::$app->user->isGuest) {
            yii::$app->getSession()->setFlash('error', 'You must be logged in to sign up to this course!');
        } else {
            $userCourse = new UserCourse();
            $userCourse->user_id = yii::$app->user->identity->getId();
            $userCourse->course_id = $id;
            if ($userCourse->save()) {
                // assign role student if no assigned yet
                $this->assignRole('student', $userCourse->user_id);
                yii::$app->getSession()->setFlash('success', 'You has been signed up to this course successfully!');
            } else {
                yii::$app->getSession()->setFlash('error', 'Error is occurred on signed up to this course! Try again.');
            }
        }
        $this->redirect(['course/index']);
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Assign role to user if role no assigned yet
     * @param $roleName string
     * @param $userId integer
     */
    protected function assignRole($roleName, $userId)
    {
        $auth = yii::$app->authManager;
        $userRoles = $auth->getRolesByUser($userId);
        if (!array_key_exists($roleName, $userRoles)) {
            $role = $auth->getRole($roleName);
            $auth->assign($role, $userId);
        }
    }

}

frontend/views/course/index.php
<?php

use common\models\Course;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\CourseSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $course common\models\Course */

$this->title = 'Courses';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php
    $courses = $dataProvider->getModels();
    foreach ($courses as $course) {
        ?>
        <div class="course">
            <div class="title"><?= Html::a(Html::encode($course->title), ['course/view', 'id' => $course->id]) ?></div>
            <div class="description">
                <p><?= Html::encode($course->description) ?></p>
            </div>
            <div class="actions">
                <?php
                if ($course->isUserSigned(yii::$app->getUser()->getId())) {
                    ?>
                    <p>Already signed on course</p>
                    <?php
                } else {
                    echo Html::a('Sign Up on Course', ['signup', 'id' => $course->id], ['class' => 'btn btn-success']);
                }
                ?>
            </div>
        </div>
        <?php
    }
    ?>

    <?php
//    echo GridView::widget([
//        'dataProvider' => $dataProvider,
//        'filterModel' => $searchModel,
//        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],
//
//            'title',
//            'description',
//
//            ['class' => 'yii\grid\ActionColumn'],
//        ],
//    ]);
    ?>

</div>

frontend/views/course/view.php
<?php

use common\models\Exam;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Course */
/* @var $exams array */
/* @var $exam common\models\Exam */
/* @var $questionDataProvider yii\data\ActiveDataProvider */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Courses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$titleQuestions = 'Questions';
?>
<div class="course-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="course-detail-view">
        <div class="form-group field-course-season_id required">
            <label class="control-label" for="view-course-season_id">Season ID</label>
            <input type="text" id="view-course-season_id" class="form-control" name="season_id"
                   value="<?= $model->season->title ?>" readonly="readonly" maxlength="255">
        </div>
        <div class="form-group field-course-title required">
            <label class="control-label" for="view-course-title">Title</label>
            <input type="text" id="view-course-title" class="form-control" name="title"
                   value="<?= $model->title ?>" readonly="readonly" maxlength="255">
        </div>
        <div class="form-group field-course-description">
            <label class="control-label" for="view-course-description">Description</label>
            <input type="text" id="view-course-description" class="form-control" name="description"
                   value="<?= $model->description ?>" readonly="readonly" maxlength="255">
        </div>
    </div>


    <h1>Course Exams:</h1>
    <div class="items exams clearfix">
        <?php
        if (empty($exams)) {
            ?>
            <h1 class="alert">There no exams yet. Come back later.</h1>
            <?php
        }
        ?>

        <div class="items-wrap clearfix">
            <?php
            foreach ($exams as $exam) {
                ?>
                <div class="item exam">
                    <h1><?= $exam->title; ?></h1>
                    <p class="description"><?= $exam->description; ?></p>
                    <p class="description">This exam can be passed from <?= date('m/d/Y', $exam->date_begin) ?> to <?= date('m/d/Y', $exam->date_end) ?></p>
                    <?php
                    if (!Yii::$app->user->isGuest && $exam->course->isUserSigned(Yii::$app->user->identity->getId())) {
                        if ($exam->canBePassed()) {
                            ?>
                            <p>
                                <?= Html::a('Pass Test', ['exam/pass/' . $exam->id], ['class' => 'btn btn-success']) ?>
                            </p>
                            <?php
                        }
                    } else {
                        ?>
                        <p>
                            <?= Html::a('To pass exam you need to be signed in to that course', ['course/index']) ?>
                        </p>
                    <?php } ?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>

</div>